backend:
  name: git-gateway
  branch: main

media_folder: 'static/images/uploads'

local_backend: true

collections:
  - label: "Items"
    name: "items"
    folder: 'content/items'
    widget: "list"
    summary: '{{fields.title}}'
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Twitch Url, name: twitchUrl, widget: string}
      - {label: YouTube Url, name: youtubeUrl, widget: string}
      - {label: Description, name: description, widget: string}
      - {label: Date Added, name: dateAdded, widget: datetime}
      - {label: Tags, name: tags, widget: select, multiple: true, options: ["tool", "stats", "guide", "reference", "community"]}
